name: 04 - Using Actions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: 04-using-actions/react-app
    # 0. Checkout the code from the repository and setup node
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
    # 1. Install deps of our react application
      - name: Install Dependencies
        run: npm ci
    # 2. Execute automated tests
      - name: Run Unit Tests
        run: npm run test