name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
        build-status:
          description: build-status
          type: choice
          options:
            - success
            - failure
          default: success

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_OUTPUT path
        run: |
          echo "$GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
          echo "$GITHUB_OUTPUT"
          echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
    outputs:
      name: ${{ steps.build.outputs.status }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.name == 'success'
    steps:
      - name: Deploy
        run: |
          echo "Deploying"